Refactor open09.c with new LTP API
linux-test-project/ltp pull request #1138
Opened 2024-02-29 10:26 UTC by ilmanzo

Refactoring with new LTP API.

The original test tries to write on a O_RDONLY file, and read on a O_WRONLY file, expecting failures. 

I could not came up with a more concise / elegant solution so improvement suggestions are welcome.

2024-03-14 13:11 UTC, acerv requested changes

2024-03-14 13:11 UTC, acerv commented on testcases/kernel/syscalls/open/open09.c
> +		break;
Better to use `if else` syntax because this looks like a `switch/case` on a boolean..

2024-03-14 15:14 UTC, acerv requested changes

2024-03-14 15:14 UTC, acerv commented on testcases/kernel/syscalls/open/open09.c
> + * - a file opened in read only mode should not be writable.
Same issue as before: it's better to provide a full description of the test, rather than a list of steps.

In this case it could be
```
This test verifies that a file opened in read only mode can't be writable and it verifies that a file opened in write only mode can't be readable.
```
You can also use `O_RDONLY` or `O_WRONLY` instead of saying `opened in read only mode`. For example, `file opened with O_RDONLY`, etc. In this case it's up to you.

2024-03-14 15:24 UTC, acerv approved these changes
LGTM

2024-04-10 16:21 UTC, closed without merging

2024-04-10 16:26 UTC, pevik commented
Thanks for your work. Actually merged 8fb23113543f074939b8d423f8bc55907bd3ac4d. 

Also removed cleanup directory (no need to unlink() just before cleanup, which deletes whole directory, the same approach use open07.c and open08.c).