setpgrp02: refactor with new LTP API
linux-test-project/ltp pull request #1148
Opened 2024-03-22 07:49 UTC by ilmanzo

This test Checks the values that setpgrp() and getpgrp() return.

The setpgrp() returns 0 on success in Linux, but, in DYNIX/ptx this call returns the new pgid.

2024-03-22 11:25 UTC, pevik commented on testcases/kernel/syscalls/setpgrp/setpgrp02.c
> +			tst_res(TFAIL, "child 1: %s", tst_strstatus(status));
We don't need `else` part at all, please remove it (LTP library does the check itself, try to `exit(1)` in child.
Also, if both parent and child were needed and code is longer, it's better to handle them with single `if` for child which exits:

```C
if (!SAFE_FORK()) {
    int oldpgrp = getpgrp();
    TST_EXP_PASS(setpgrp());
    exit(TST_RET);
}

... // some parent code

2024-03-22 11:25 UTC, pevik commented on testcases/kernel/syscalls/setpgrp/setpgrp02.c
> +	if (pid == 0) { // child
We don't need this comment (please use just `if (!SAFE_FORK()) {`).

2024-03-22 11:31 UTC, pevik requested changes
Parent handling is not needed.

2024-03-27 10:18 UTC, ilmanzo commented
> Parent handling is not needed.

thanks for the useful review; removed parent handling and comments as requested.

2024-03-28 12:49 UTC, closed without merging