mincore02 : refactor with new LTP API
linux-test-project/ltp pull request #1153
Opened 2024-04-12 15:28 UTC by ilmanzo

This test case provides a functional validation for mincore system call.

2024-04-18 08:58 UTC, acerv requested changes

2024-04-18 08:58 UTC, acerv commented on testcases/kernel/syscalls/mincore/mincore02.c
> + * [Description]
Very nit: pls add a space after `[Description]`

2024-04-18 08:58 UTC, acerv commented on testcases/kernel/syscalls/mincore/mincore02.c
> +	SAFE_MUNLOCK(addr, size);
What if `mmap()` fails? `addr` needs to be checked here also

2024-04-18 08:58 UTC, acerv commented on testcases/kernel/syscalls/mincore/mincore02.c
> +	TST_EXP_PASS_SILENT(mincore(addr, NUM_PAGES * page_size, vec));
We are testing `mincore`, so rather than silent pass, we need a pass check as well

2024-04-18 08:58 UTC, acerv commented on testcases/kernel/syscalls/mincore/mincore02.c
> +	/* fill the temporary file with $NUM_PAGES pages of data */
The code is pretty clear, so we don't need comments here

2024-04-18 08:58 UTC, acerv commented on testcases/kernel/syscalls/mincore/mincore02.c
> +	/* check status of pages */
no need to comment

2024-04-18 12:28 UTC, ilmanzo commented on testcases/kernel/syscalls/mincore/mincore02.c
> +	SAFE_MUNLOCK(addr, size);
I understand that SAFE_MMAP on [line 50](https://github.com/linux-test-project/ltp/blob/08b555d5c09893483f8e9d1c781fe69d3a248980/testcases/kernel/syscalls/mincore/mincore02.c#L50) addresses a possible `mmap()` fail ?

2024-04-18 18:45 UTC, pevik requested changes
Please update these 3 small things.

2024-04-18 18:45 UTC, pevik commented on testcases/kernel/syscalls/mincore/mincore02.c
> +	SAFE_MUNLOCK(addr, size);
No, @acerv is correct, `addr` must be be protected by `if (addr)` check. Try: 

```diff
+++ testcases/kernel/syscalls/mincore/mincore02.c
@@ -47,6 +47,7 @@ static void setup(void)
        int fd = SAFE_OPEN("mincore02", O_CREAT | O_RDWR, 0600);
 
        SAFE_WRITE(SAFE_WRITE_ALL, fd, buf, size);
+       tst_brk(TBROK, "pretend wrote failed :)");
        addr = SAFE_MMAP(NULL, size, PROT_READ | PROT_WRITE | PROT_EXEC, MAP_SHARED, fd, 0);
 
        SAFE_MLOCK(addr, size);
```

```sh
$ ./mincore02
tst_test.c:1741: TINFO: LTP version: 20240129-176-gfc21a8b5b
tst_test.c:1625: TINFO: Timeout per run is 0h 00m 30s
mincore02.c:50: TBROK: pretend wrote failed :)
mincore02.c:33: TWARN: munlock() failed: ENOMEM (12)
```

2024-04-18 18:45 UTC, pevik commented on testcases/kernel/syscalls/mincore/mincore02.c
> +		close(fd);
nit:
```C
if (fd > 0)
    SAFE_CLOSE(fd);

2024-04-18 18:45 UTC, pevik commented on testcases/kernel/syscalls/mincore/mincore02.c
>  static int page_size;
`getpagesize()` result does not need to be stored as a value. Effectively we use always only `getpagesize() * NUM_PAGES`.

2024-04-19 06:54 UTC, ilmanzo commented
> Please update these 3 small things.

done, thank you both for the great suggestions :)

2024-04-19 07:26 UTC, closed without merging